### ISSUE TITLE
Cancel Invoice

### ISSUE THREAD

**Issue by bagaskarala** [bagaskarala/sigap#48]
## issue
ketika buat faktur tunai-perpustakaan dan tunai-showroom, stok langsung berkurang, tapi jika faktur dibatalkan, stok tidak kembali.

**Comment by michaelr1300** [comment]
Di fix di #46 commit f066a1b mas

**Comment by michaelr1300** [comment]
Sudah ditanyakan ke Staff UGM Press, ternyata jenis faktur tunai hanya ada sumber dari gudang dan dari perpus. Sumber showroom hanya untuk faktur showroom. 

Faktur tunai gudang akan mengurangi stock gudang (sama seperti sebelumnya) dan faktur tunai perpus akan mengurangi stock perpus

https://user-images.githubusercontent.com/46708593/120879209-031b3300-c5ec-11eb-81e4-e766a1a84e66.mp4

Dropdown daftar buku hanya menampilkan buku yang stocknya > 0. Saat sumber faktur diganti, dropdown juga ganti menyesuaikan. Dropdown pertama menampilkan stock yang ada di gudang. Setelah diganti hanya menampilkan stock yang ada di perpus

https://user-images.githubusercontent.com/46708593/120683318-b0485b00-c4c7-11eb-96f0-99e5f8a25df8.mp4
